### PR TITLE
Organize and improve type safety

### PR DESCRIPTION
**Pull request by yenbekbay**

### CODE REVIEW

**Comment by yenbekbay** [comment]
Need to change "Root directory" on Vercel to `apps/web` before merging this.

**Comment by tonyxiao** [comment]
There's no vercel.json that can configure this on a per commit / branch basis?

**Comment by tonyxiao** [comment]
@yenbekbay PR was in draft status. Intentional or ready for merge/

**Comment by yenbekbay** [comment]
> There's no vercel.json that can configure this on a per commit / branch basis?

I've looked and there's no option for that. Seems like it's only configurable from the website.

> @yenbekbay PR was in draft status. Intentional or ready for merge/

Ready for review. Changing status.

**Comment by tonyxiao** [comment]
Got 3 errors, are these new / did they happen to you?
image
image
image

**Comment by tonyxiao** [comment]
pressed the merge button a bit soon. was in the middle of testing

**Comment by tonyxiao** [comment]
This is on the / page

**Comment by tonyxiao** [comment]
image
Also checked similar error happen on other pages.

**Comment by yenbekbay** [comment]
They're technically warnings. It's still the same problem with params being `undefined` on first render

**Pull request merged**
